In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9337, 6002, 6924, 9573],
 [9337, 6002, 6924, 6717],
 [9337, 3210, 6924, 1206],
 [5115, 865, 1632, 4458, 320],
 [5115, 865, 1632, 4458, 7315],
 [212, 9337, 8827, 6924, 6666],
 [3831, 7651, 8453, 4458]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9337 6002 6924 9573]
 [   0    0    0    0 9337 6002 6924 6717]
 [   0    0    0    0 9337 3210 6924 1206]
 [   0    0    0 5115  865 1632 4458  320]
 [   0    0    0 5115  865 1632 4458 7315]
 [   0    0    0  212 9337 8827 6924 6666]
 [   0    0    0    0 3831 7651 8453 4458]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step


array([[[ 4.83816862e-03, -2.76718289e-03,  1.10776797e-02,
         -4.20402065e-02, -4.37758677e-02,  2.86304243e-02,
         -4.80170958e-02,  1.06030330e-02,  7.61561468e-03,
         -5.34214824e-03],
        [ 4.83816862e-03, -2.76718289e-03,  1.10776797e-02,
         -4.20402065e-02, -4.37758677e-02,  2.86304243e-02,
         -4.80170958e-02,  1.06030330e-02,  7.61561468e-03,
         -5.34214824e-03],
        [ 4.83816862e-03, -2.76718289e-03,  1.10776797e-02,
         -4.20402065e-02, -4.37758677e-02,  2.86304243e-02,
         -4.80170958e-02,  1.06030330e-02,  7.61561468e-03,
         -5.34214824e-03],
        [ 4.83816862e-03, -2.76718289e-03,  1.10776797e-02,
         -4.20402065e-02, -4.37758677e-02,  2.86304243e-02,
         -4.80170958e-02,  1.06030330e-02,  7.61561468e-03,
         -5.34214824e-03],
        [-1.39661916e-02, -5.21958992e-03, -1.57940872e-02,
         -2.06090510e-04,  1.34273209e-02, -3.72978672e-02,
          1.54504664e-02, -4.84762564e-02,  4.529298

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9337, 6002, 6924, 9573], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>