In [4]:
#nnumpy: is a fundamental  important library for scientific computing in python
#use in deep learning,machine learning

import numpy as np

#creating array using numpy
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr1=np.array([1,2,3,4,5])
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2.shape)

(2, 3)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))# 2d array with one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#numpy vectorised operation
ar1=np.array([1,2,3,4,5,6])
ar2=np.array([10,20,30,40,50,60])
print("addition",ar1+ar2)# add 2 array element by element
print("subtraction",ar2-ar1)
print("multiplication",ar1*ar2)

addition [11 22 33 44 55 66]
subtraction [ 9 18 27 36 45 54]
multiplication [ 10  40  90 160 250 360]


In [19]:
#universal operation
arr=np.array([1,2,3,4,5,6])
#squareroot
print(np.sqrt(arr))

#sine
print("sine",np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
sine [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [20]:
#statistical normalization
#mean is 0 and sd is 1
data=np.array([1,2,3,4,5,6])

#mean
mean=np.mean(data)

#standard deviation
sd=np.std(data)

normalised_data=(data-mean)/sd
print(normalised_data)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
