### logistic regression
use for binart classification
when our answer get out of bound using linear regression
we create a sigmoid curve

### sigmoid activation

for line h= o + o1 x
sigmoid is h=1/(1+e^-z)
where z is  o + o1 x



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#creatoing a dataset
from sklearn.datasets import make_classification


In [3]:
X,y=make_classification(n_samples=10000,n_features=10,n_classes=2,random_state=42)

In [4]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0     0.633563  0.357385 -0.503931  0.935066  0.647981 -0.050796 -1.933989   
1     1.283905  1.109459 -0.908953  1.006586  0.492219  1.107295  1.243526   
2    -0.966476 -0.593314  0.458020  1.032323  1.283685 -0.317640  1.499045   
3     2.429309 -1.306530 -1.869925  3.092164  2.028800 -0.879635 -0.393494   
4    -1.204798  0.078464  0.705181  0.224765  0.618707  1.534946 -0.302288   
...        ...       ...       ...       ...       ...       ...       ...   
9995 -1.606404  0.228927  0.959690  0.145821  0.682755 -0.927143 -0.280438   
9996  1.154048 -0.120265 -0.643621 -0.467386 -0.825604  0.725398 -1.439272   
9997  0.841468 -0.593749 -0.391671 -0.955036 -1.169619  0.683856 -1.629486   
9998  1.080252 -0.607761 -0.488605 -1.338506 -1.605447 -1.689724  0.202908   
9999 -1.205338 -1.719647  0.994358 -2.060993 -1.493417 -0.664010  0.718480   

             7         8         9  
0     2.081684  0.041266 -0.258298  
1    -0.172200  1.150359  0.147744  
2     0.434477  0.423678  1.251380  
3    -0.101213 -1.624066  0.443553  
4     2.325055  0.495505  0.538133  
...        ...       ...       ...  
9995  0.789222 -1.330100 -1.463687  
9996 -1.132146  1.511610 -0.114986  
9997  0.289335 -0.434358 -1.271335  
9998  0.291496  0.827980 -1.069399  
9999 -0.305819 -1.405728 -0.703207  

[10000 rows x 10 columns]

In [5]:
y

array([1, 1, 1, ..., 0, 0, 0], shape=(10000,))

In [6]:
#train test split
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [8]:
#model training
from sklearn.linear_model import LogisticRegression


In [9]:
logic=LogisticRegression()

In [10]:
logic.fit(X_train,y_train)

LogisticRegression()

In [11]:
y_pred=logic.predict(X_test)

In [12]:
y_pred

array([1, 1, 1, ..., 0, 1, 0], shape=(3000,))

In [13]:
#preformance matrics
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [14]:
sc=accuracy_score(y_test,y_pred)
print(sc)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.8923333333333333
[[1329  155]
 [ 168 1348]]


In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.90      0.89      1484
           1       0.90      0.89      0.89      1516

    accuracy                           0.89      3000
   macro avg       0.89      0.89      0.89      3000
weighted avg       0.89      0.89      0.89      3000



In [16]:
### hyper parameter tuning

In [17]:
model=LogisticRegression()

In [18]:
penalty=['l1','l2','elasticney']
c_value=[100,10,0.1,0.01,1]
solver=['newton-cg','saga','sag','liblinear','lbfgs']

In [19]:
params=dict(penalty=penalty,C=c_value,solver=solver)

In [20]:
##grid search cv
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv=StratifiedKFold()
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv)

In [21]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 0.1, 0.01, 1],
                         'penalty': ['l1', 'l2', 'elasticney'],
                         'solver': ['newton-cg', 'saga', 'sag', 'liblinear',
                                    'lbfgs']},
             scoring='accuracy')


In [22]:
grid.fit(X_train,y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 0.1, 0.01, 1],
                         'penalty': ['l1', 'l2', 'elasticney'],
                         'solver': ['newton-cg', 'saga', 'sag', 'liblinear',
                                    'lbfgs']},
             scoring='accuracy')

In [23]:
grid.best_params_

{'C': 0.01, 'penalty': 'l1', 'solver': 'liblinear'}

In [24]:
grid.best_score_

np.float64(0.8917142857142857)

In [25]:
###randomised search cv
from sklearn.model_selection import RandomizedSearchCV

In [26]:
randoms=RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=cv)

In [27]:
randoms.fit(X_train,y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 0.1, 0.01, 1],
                                        'penalty': ['l1', 'l2', 'elasticney'],
                                        'solver': ['newton-cg', 'saga', 'sag',
                                                   'liblinear', 'lbfgs']},
                   scoring='accuracy')

In [28]:
randoms.best_score_

np.float64(0.891)